### ISSUE TITLE
Does Server work with iOS Emulator APP too?

### ISSUE THREAD

**Issue by rngtng** [getsenic/nuimo-websocket-server-osx#1]
Hey
I'd like to use the websocket server to connect the nuimo emulator in my iPhone. But somehow, the server doesn't discover the emulator. Does this actually work? What's the trick?

Cheers Tobi

Update: I'm running the latest versions on iPhone & Mac OS X

**Comment by larsblumberg** [comment]
Hi Tobias, [please use the Android emulator](https://senic.com/developers#emulator) for now. I'm also experiencing issues with the WebSocket Server app not being able to connect to the iOS emulator.

Will keep you updated here!

**Comment by larsblumberg** [comment]
@rngtng Which MacBook model are you using? Older MacBooks < 2012 don't support BLE. Mine is from 2011 and only works with a BLE USB dongle.

**Comment by rngtng** [comment]
I've a late 2012 MacBook Pro. According to the specs, BLE is supported. I'll see if I can get an Android device and run the test again. thx

**Comment by larsblumberg** [comment]
@rngtng Did you succeed to connect with the Android emulator?

**Comment by rngtng** [comment]
@larsblumberg sorry didn't find any time to check on Android yet. But got it finally running. see https://github.com/getsenic/nuimo-emulator-ios/pull/3

**Comment by larsblumberg** [comment]
Thanks a lot!
