### ISSUE TITLE
Can't start Nuimo WebSocket Server

### ISSUE THREAD

**Issue by yougotashovel** [getsenic/nuimo-websocket-server-osx#2]
Can you elaborate on step 1. Start Nuimo WebSocket Server.

Tried opening up in xcode and building, but getting failed to build.  Would be great if there was a ready made build of this.

Thanks

**Comment by yougotashovel** [comment]
Found the issue.  Needed to install cocoapods, then run 'pod install'  Once i did there was an issue preventing the build due to no target being set for the pods.

I can't push to the repo, so here's the fix.  'Podfile' should be updated to this:

```
use_frameworks!

target 'NuimoWebSocketServer' do
   pod 'NuimoSwift'
   pod 'PocketSocket'
end
```

**Comment by larsblumberg** [comment]
Thanks for reporting @yougotashovel, `Podfile` is now updated to be compatible with Cocoapods 1.0 release
