### ISSUE TITLE
Battery level

### ISSUE THREAD

**Issue by moifort** [getsenic/nuimo-websocket-server-osx#3]
It's possible with the web socket to know the battery level of the nuimo?

**Comment by larsblumberg** [comment]
Hi @moifort – it's possible but not yet supported. Let me see if I can quickly add it.

**Comment by moifort** [comment]
If you can implement it, it would be awesome! But if it's take too much time for you I will see if I can make a pull request :)

Thibaut.

**Comment by larsblumberg** [comment]
Firmware version (prefix _V_) and battery level (prefix _%_) are now immediately reported when you connect your web socket(s). Additionally, battery level is reported every 3 minutes.

**Comment by larsblumberg** [comment]
PS: We also made an compiled app available at https://senic.com/developers

**Comment by moifort** [comment]
Oooh! Thank you!!! You are awesome \o/!!!!

Thibaut.
