### ISSUE TITLE
Battery issue

### ISSUE THREAD

**Issue by moifort** [getsenic/nuimo-websocket-server-osx#4]
I use `nuimo-websocket-server-osx` with bluetooth connected to my Nuimo device. But I experiment a little problem, my nuimo device has an autonomy of only few days :(.

 It is normal?

**Comment by larsblumberg** [comment]
Hi! We're updating constantly the firmware version to increase battery duration. Please expect a firmware update within the next few weeks.

**Comment by moifort** [comment]
Oki, no problem!!!! 

Thank you!
